version: "3.9"
services:
  bedrock:
    image: abeyuki/minecraft-bedrock-arm64:1.19.81.01
    ports:
      - 19132:19132/udp
    stdin_open: true
    tty: true
    environment:
      EULA: "TRUE"
      GAMEMODE: survival
      DIFFICULTY: normal
    volumes:
      - bedrock_data:/bedrock-server
volumes:
  bedrock_data: