version: "3.9"
services:
  bedrock:
    image: abeyuki/minecraft-bedrock-arm64:1.18.31.04
    ports:
      - 19132:19132/udp
    stdin_open: true
    tty: true
    environment:
      EULA: "TRUE"
      GAMEMODE: survival
      DIFFICULTY: normal
    command: bash -c "box64 /bedrock-server/bedrock_server"
    volumes:
      - bedrock_data:/bedrock-server
volumes:
  bedrock_data: